[tool.bumpversion]
current_version="0.1.0"
commit=true
tag = true
tag_name = "v{new_version}"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]

[[tool.bbumpversion.files]]
filename = "setup.py"
search = "version='{current_version}'"
replace = "version='{new_version}'"

[[tool.bumpversion.files]]
filename="mkdocs_protobuf_plugin/__init__.py"
search = "__version__ = '{current_version}'"
replace = "__version__ = '{new_version}'"